FROM kibana:5

# The following is a crude hack, that will make Kibana wait until
# Elasticsearch server is up and running, and then connect on it.

COPY startup.sh /tmp/startup.sh
RUN apt-get -qq update && \
    apt-get install -qq -y netcat bzip2 && \
    chmod +x /tmp/startup.sh

CMD ["/tmp/startup.sh"]
